FLAGS=CPPFLAGS='-D_PTW32_STATIC_LIB' LDFLAGS='-static -lws2_32 -lpthread' NAME=tcptunnel.exe

all:
	$(MAKE) -C src $(FLAGS)

install:
	$(MAKE) -C src $(FLAGS) install

uninstall:
	$(MAKE) -C src $(FLAGS) uninstall

clean:
	$(MAKE) -C src $(FLAGS) clean

